#!/bin/bash

echo "About to commit the following patches: "
echo

git --no-pager log upstream/master..HEAD

echo
echo "Make sure you remembered to move ChangeLog entries to their proper places!"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    git push ssh://palves@sourceware.org/git/binutils-gdb.git HEAD:master
fi
