#!/bin/bash

# Copyright (C) 2013 Pedro Alves.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Diff two DejaGnu sum files, and run the output through deja-color
# for colorization.
#
# Usage:
#  deja-diff build.before/gdb/testsuite/gdb.sum build.after/gdb/testsuite/gdb.sum

#!/bin/bash

FILE1=$1
shift
FILE2=$1
shift

# FIXME: should really create a temp file properly...
sed 's,Running .*/src/gdb/,src/gdb/,g' < $FILE1 > /tmp/deja-diff-file-1
sed 's,Running .*/src/gdb/,src/gdb/,g' < $FILE2 > /tmp/deja-diff-file-2

diff -up /tmp/deja-diff-file-1 /tmp/deja-diff-file-2 "$@" | deja-color | less
