#!/bin/gawk -f

# Copyright (C) 2013 Pedro Alves.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Colorize a DejaGnu sum unified diff.  Regressions are displayed in
# red, progressions in green.

# Usage:
#  diff -up 1/gdb.sum 2/gdb.sum | deja-color

function colorize(string, color) { printf ("\033[1;%dm%s\033[0m ", color, string); }

function print_messages(line, messages, minus_color, plus_color) {
	for (idx in messages) {
		msg = messages[idx]
		if (line ~ "-" msg) {
			print colorize(line, minus_color)
			return 1
		}
		if (line ~ "+" msg) {
			print colorize(line, plus_color)
			return 1
		}
	}
	return 0
}

{
	red=31
	green=32

	split ("PASS KPASS XPASS", good, " ")
	split ("FAIL KFAIL XFAIL ERROR UNRESOLVED UNSUPPORTED DUPLICATE PATH", bad, " ")

	if (!print_messages($0, good, red, green) \
	    && !print_messages($0, bad, green, red)) {
		print $0
	}
}
