#!/bin/bash

# Copyright (C) 2014 Pedro Alves.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Like 'stg series', but also shows each patch's git hash.  Arguments
# are passed directly to "stg series".

stg series "$@" | \
    while read line; do
      patch=`echo $line | awk '{ print $2 }'`
      hash=`stg show $patch 2>/dev/null | head -n 1 | awk '{ print $2 }'`
      echo "$hash | $line"
    done
