#!/bin/bash

# Copyright (C) 2014 Pedro Alves.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Like 'stg branch --clone', but stays in the current branch.

set -e

function usage () {
    echo >&$1 \
        "usage: $0 [BACKUP_NAME]"
}

if [ $# -eq 1 ]; then
    backup_branch=$1
elif [ $# -eq 0 ]; then
    backup_branch=""
else
    usage 2
    exit 1
fi

curr_branch=$(stg branch)
stg branch --clone $backup_branch

# Switch back to the original branch.
# "git co -q" is quieter than "stg branch".
git checkout -q $curr_branch
